apiVersion: apps/v1
kind: Deployment
metadata:
  name: automation-deployment-test-dev
  namespace: test-dev
  labels:
    app: automation-test-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: automation-test-dev
  template:
    metadata:
      labels:
        app: automation-test-dev
    spec:
      containers:
        - name: automation-test-dev
          image: ubilitycr.azurecr.io/dev-automation:V1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      dnsPolicy: ClusterFirst
      tolerations:
      - key: backup-node-1
        operator: Equal
        value: backups-only
        effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name:  automation-service-test-dev
  namespace: test-dev
  labels:
    app: automation-test-dev
spec:
  loadBalancerIP: 20.187.163.161
  type: LoadBalancer
  selector:
    app: automation-test-dev
  ports:
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443

